intern_project/cookapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', views.top, name='top'),
    path('login/', views.login_view.as_view(), name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup', views.SignupView.as_view(), name='signup'),
    path('signup_complete',views.signup_complete,name='signup_complete'),
    path('home', views.home, name='home'),
    path('friends', views.friends, name='friends'),
    path('submission', views.SubmissionView, name='submission'),
    path('friends_content/<int:id>', views.friends_content, name='friends_content'),
    path('my_content/<int:id>', views.my_content, name='my_content'),
    path('friends_list', views.friends_list, name='friends_list'),
    path('friends_profile/<int:id>', views.friends_profile, name='friends_profile'),
    path('setting', views.setting, name='setting'),
    path('friends_add_before', views.friends_add_before, name='friends_add_before'),
    path('my_content_update/<int:pk>', views.ContentUpdateView.as_view(), name='my_content_update'),
    path('my_content_delete/<int:pk>', views.MyContentDeleteView.as_view(), name='my_content_delete'),
    path('friends_add_after/<str:userID>', views.friends_add_after, name="friends_add_after"), 
    path('user_update/<int:pk>',views.UserUpdateView.as_view(),name='user_update'),
    path('logout2',LogoutView.as_view(),name='logout2'),
    path('user_delete/<int:pk>',views.UserDeleteView.as_view(),name='user_delete'),
    path('password_change',views.PasswordView.as_view(),name='password_change'),
    path('setting_complete',views.setting_complete,name='setting_complete'),
]

intern_project/intern_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cookapp.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

intern_project/cookapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.fields import related
from django.contrib.auth.validators import UnicodeUsernameValidator



class User(AbstractUser):
    #アイコン画像
    icon = models.ImageField(blank=True, null=True,default='グループ 481.png')
    username_validator = UnicodeUsernameValidator()
    userID = models.CharField(max_length = 15, null = True)

    username = models.CharField(
        verbose_name='ユーザーネーム',
        max_length=20,
        validators=[username_validator]
        
    )

    email = models.EmailField(
        max_length=254,
        null=True, 
        verbose_name='メールアドレス') #追記　エガワ　verbose_name
  



class Submission(models.Model):
    #外部キー
    submissionconnection = models.ForeignKey(User, on_delete=models.CASCADE, related_name='submissionconnection')
    #画像
    image = models.ImageField(upload_to='media', null=True)

    CATEGORY = (
        (11, '和食'),
        (12, '洋食'),
        (13, '中華'),
        (14, 'アジア'),
        (15, 'カレー'),
        (16, '焼肉'),
        (17, '鍋'),
        (18, '麺類'),
        (19, '軽食'),
        (20, 'スイーツ'),
        (21, '飲食'),
        (22, 'その他'),
    )
    #カテゴリー
    category = models.IntegerField(choices=CATEGORY, null=True)
    PUBLIC_PRIVATE = (
        (11, '公開'),
        (12, '非公開'),
    )
    #公開/非公開
    public_private = models.IntegerField(choices=PUBLIC_PRIVATE, null=True)
    #日付時間
    date = models.DateField(null=True)
    #場所
    place = models.CharField(max_length=50, null=True)
    #コメント
    comment = models.CharField(max_length=2000, null=True)
    time = models.IntegerField(default=0)

class Thread(models.Model):
    threadconnection_image = models.ForeignKey(Submission, on_delete=models.CASCADE, related_name='threadconnection_image', null=True)
    threadconnection_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='threadconnection_user', null=True)
    thread = models.CharField(max_length=150, null=True)
    
class Threadlist(models.Model):
    threadlistconnection_thread = models.ForeignKey(Thread, on_delete=models.CASCADE, related_name='threadlistconnection', null=True)
    threadlistconnection_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='threadlistconnection', null=True)
    threadlist = models.CharField(max_length=150, null=True)

class Friends(models.Model):

    users = models.ForeignKey(User, related_name='friends', on_delete=models.CASCADE, null=True)#友達
    current_user = models.ForeignKey(User, related_name='owner', on_delete=models.CASCADE, null=True)#自分


class Like(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='user', null=True)
    submission = models.ForeignKey(Submission,on_delete=models.CASCADE,related_name='submission', null=True)

intern_project/cookapp/views.py
from django.db import models

from django.forms.utils import pretty_name
from django.http import request
from django.shortcuts import redirect, render

from django.db.models.fields import EmailField

from django.forms.utils import to_current_timezone
from django.http import request
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from .models import Submission, User, Thread, Friends, Threadlist, Like
from .forms import PasswordForm, SubmissionForm, FriendsForm, ThreadlistForm, SearchForm, UpdateForm

from django.views.generic import CreateView,UpdateView,DeleteView
from django.contrib import messages
from django.utils.crypto import get_random_string

from django.contrib.auth import authenticate, login
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView,PasswordChangeView
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic.edit import CreateView
from .forms import SignupForm, ThreadForm
from django.contrib.auth.decorators import login_required, user_passes_test

from django.db.models import Q

from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import EmailAuthenticationForm
from django.contrib.staticfiles.storage import staticfiles_storage

# Create your views here.
def top(request):
    return render(request, 'cookapp/top.html')

class login_view(LoginView):
    authentication_form = EmailAuthenticationForm
    template_name = "cookapp/login.html"
    success_url = reverse_lazy('home')
    


def logout(request):
    return render(request,'cookapp/logout.html')





class SignupView(CreateView):
    model = User
    form_class = SignupForm
    template_name = "cookapp/signup.html"
    success_url = reverse_lazy('signup_complete')

    def form_valid(self,form):
        user = form.save(commit = False)
        user.userID = get_random_string(15)
        user.save()
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return HttpResponseRedirect(self.success_url)

    def form_invalid(self,form):
        messages.error(self.request,"失敗")
        return super().form_invalid(form)
@login_required
def signup_complete(request):
    return render(request,'cookapp/signup_complete.html')




@login_required
def home(request):
    user = request.user
    content = Submission.objects.filter(submissionconnection=user)
    if content.exists():
        randomcontent = content.order_by('?')[0]
        content = content.exclude(id = randomcontent.id)
        params = {
            'user': user,
            'content': content,
            'randomcontent': randomcontent,
            }
    else:
        params = {
            'user': user,
            }

    return render(request, 'cookapp/home.html', params)
@login_required
def friends(request):
    user = request.user
    params ={
        'form':SearchForm,
    }

    if Friends.objects.filter(current_user = request.user).exists():
        friendslist = Friends.objects.filter(current_user = request.user)
        if Like.objects.filter(user = user).exists():
                like = Like.objects.filter(user = user)
        if request.method == 'POST':
            word = request.POST['word']
            if word == '和食':
                word = 11
            if word == '洋食':
                word = 12
            if word == '中華':
                word = 13
            if word == 'アジア':
                word = 14
            if word == 'カレー':
                word = 15
            if word == '焼肉':
                word = 16
            if word == '鍋':
                word = 17
            if word == '麺類':
                word = 18
            if word == '軽食':
                word = 19
            if word == 'スイーツ':
                word = 20
            if word == '飲食':
                word = 21
            if word == 'その他':
                word = 22
   
            place = Submission.objects.filter(place__icontains=word)
            category = Submission.objects.filter(category__icontains=word)
  
            params ={
                'form':SearchForm,
                'category':category,
                'place':place,
                'friendslist':friendslist,
                'like':like,
            }
            return render(request, 'cookapp/friends.html', params)
        if Submission.objects.exclude(submissionconnection = user).exists():
            submission_exclude = Submission.objects.exclude(submissionconnection = user)
            params ={
                'submission_exclude':submission_exclude,
                'user':user,
                'form':SearchForm,
                'friendslist': friendslist,
            }       
            if Like.objects.filter(user = user).exists():
                like1 = Like.objects.filter(user = user)
                submission_exclude = Submission.objects.exclude(submissionconnection = user)
                params ={
                    'submission_exclude':submission_exclude,
                    'user':user,
                    'like':like,
                    'like1':like,
                    'form':SearchForm,
                    'friendslist': friendslist,
                }
                return render(request, 'cookapp/friends.html',params)
            return render(request, 'cookapp/friends.html',params)
    return render(request, 'cookapp/friends.html', params)
    
@login_required
def SubmissionView(request):
    params = {
        'form': SubmissionForm(),
    }
    if request.method == 'POST':
        form = SubmissionForm(request.POST, request.FILES)
        if form.is_valid():
            submission = form.save(commit=False)
            submission.submissionconnection = request.user
            submission.save()
        else:
            params['form'] = form
            return render(request, 'cookapp/submission.html', params)
        return redirect('home')

    return render(request, 'cookapp/submission.html', params)

@login_required
def friends_content(request,id):
    content = Submission.objects.get(id = id)
    content.time = content.time + 1
    content.save()
    threadlist = Thread.objects.filter(threadconnection_image = content)


    thread = Thread.objects.filter(threadconnection_image = content)
    threadlist = Threadlist.objects.all()
    form1 = ThreadlistForm()
    if request.method == 'POST':
        if 'thread1' in request.POST:
            print(request.POST)
            form = ThreadForm(request.POST)
            if form.is_valid():
                form = form.save(commit=False)
                form.threadconnection_image = content
                form.threadconnection_user = request.user
                form.save()
                return redirect('friends_content', content.id)
        elif 'th' in request.POST:
                print(type(request.POST['th']))
                number = int(request.POST['th'])
                print(type(number))
                form2 = ThreadlistForm(request.POST)
                if form2.is_valid():
                    form2 = form2.save(commit=False)
                    form2.threadlistconnection_thread = thread[number]
                    form2.threadlistconnection_user = request.user
                    form2.save()
                    return redirect('friends_content', content.id)
        if 'like' in request.POST:
            user = request.user
            if Like.objects.filter(user=user,submission=content).exists():
                like= Like.objects.get(user=user,submission=content)
                like.delete()
                return redirect('friends_content', content.id)
            else:
                Like.objects.create(user=user,submission = content)
                return redirect('friends_content', content.id)
                
    if content.category == 11:
        content.category = '和食'
    if content.category == 12:
        content.category = '洋食'
    if content.category == 13:
        content.category = '中華'
    if content.category == 14:
        content.category = 'アジア'
    if content.category == 15:
        content.category = 'カレー'
    if content.category == 16:
        content.category = '焼肉'
    if content.category == 17:
        content.category = '鍋'
    if content.category == 18:
        content.category = '麺類'
    if content.category == 19:
        content.category = '軽食'
    if content.category == 20:
        content.category = 'スイーツ'
    if content.category == 21:
        content.category = '飲食'
    if content.category == 22:
        content.category = 'その他'
    if content.public_private == 11:
        content.public_private = '公開'
    if content.public_private == 12:
        content.public_private = '非公開'
    if Like.objects.filter(user=request.user,submission=content).exists():
        like= Like.objects.get(user=request.user,submission=content)
        params = {
            'content': content,
            'form': ThreadForm(),
            'threadlist': threadlist,
            'time': content.time,
            'thread': thread,
            'form1': form1,
            'like': like,
        }
        return render(request, 'cookapp/friends_contents.html',params)
    params = {
        'content': content,
        'form': ThreadForm(),
        'threadlist': threadlist,
        'time': content.time,
        'thread': thread,
        'form1': form1,
    }
    return render(request, 'cookapp/friends_contents.html',params)
@login_required
def my_content(request, id):
    content = Submission.objects.get(id = id)
    thread = Thread.objects.filter(threadconnection_image = content)
    threadlist = Threadlist.objects.all()
    form1 = ThreadlistForm()
    if request.method == 'POST':

intern_project/cookapp/templates/cookapp/base.html
{% load static %} 
{% load widget_tweaks %} 
<!doctype html>
<html lang="ja">
<head>
    {% block extrastyle %}
    
    {% endblock extrastyle %} 
    
    <link rel="stylesheet" href="../static/css/base.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kosugi+Maru&display=swap" rel="stylesheet">
    <meta charset="utf-8" name="viewport" content="width=device-width">
</head>
<body>
    <header>
        {% block header %}
        {% endblock header %}
    </header>
    <main>
            {% block main %}
            {% endblock  %}
    </main>
    <footer>
        <!------------- ここが引き継がれる -------------------------------->
        <div class="footer-container">
                <div class="footer-button" ><a href="{% url 'home' %}"><img src="{% static '../static/svg/home_orange.svg' %}" alt="" id="button1"></a></div>
                <div class="footer-button" ><a href="{% url 'friends' %}"><img src="{% static '../static/svg/friends.svg' %}" alt="" id="button2"></a></div>
                <div class="footer-button" ><a href="{% url 'submission' %}"><img src="{% static '../static/svg/submission.svg' %}" alt="" id="button3"></a></div>
                <div class="footer-button" ><a href="{% url 'friends_add_before' %}"><img src="{% static '../static/svg/friend_add_before.svg' %}" alt="" id="button4"></a></div>
        </div>
        <!-- ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー -->
    </footer>
<script src="../static/javascript/base.js"></script>
{% block script %}
{% endblock script %}
</body>
</html>

intern_project/cookapp/templates/cookapp/friends_add_before.html
{% extends 'cookapp/base.html' %}
{% load static %}
{% load widget_tweaks %}
<!doctype html>
<html lang="ja">
<head>
    {% block extrastyle %}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/friends_add_before.css' %}" />
        <title>友達追加（追加前）</title>
    {% endblock extrastyle %}
</head>
<body>
    {% block header %}
        <div class="title">
            <h1 class="h1">友だち追加</h1>
        </div>
    {% endblock header %}
    {% block main %}
        <div class="form_field">
            <form method="post" enctype="multipart/form-data" class='searchform'>
            {% csrf_token %}
            <div class="searchfield">
                <h2 class="table_title">ID検索</h2>
                <div class='usrtID'>{{ form.userID }}</div>
            </div>
            <button class='button' type="submit">
                <img class='img' src="{% static 'svg/グループ 236.svg' %}"/>
            </button>
            </form>
        </div>
        <div class="myID">
            <div class='myID_contents'>
                <div class="myID_id">
                    <h2 class="myID_title">あなたのID</h2>
                    {{myuserID}}
                </div>
                <p class="myID_doc">友達の検索ボックスに、大文字と小文字を区別して正確に入力して下さい</p>
            </div>
        </div>
    {% endblock main %}
</body>
</html>

intern_project/cookapp/templates/cookapp/friends_contents.html
{% extends 'cookapp/base.html' %}
{% load static %}
{% load widget_tweaks %}
<!doctype html>
<html lang="ja">
{% block extrastyle %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/friends_content.css' %}" />
  {% endblock extrastyle %}
</head>
<header>
    {% block header %}
        <div class="header-container">
            <a class = "Link" href="{% url 'friends' %}" class='friends-image'><img src="{% static 'svg/← (2).svg' %}" class='header-image'/></a>
    {% if content.submissionconnection.icon %}
            <div class="header-icon"><a href="{% url 'friends_profile' content.submissionconnection.id %}"><img src="{{content.submissionconnection.icon.url}}" style='border-radius:50px;' width="30" height="30"></a></div>
    {% endif %}
            <div class="header-name"><a href="{% url 'friends_profile' content.submissionconnection.id %}">{{content.submissionconnection.username}}</a><div>
        </div>
    {% endblock header %}
</header>
<body>
{% block main %}
    <div class="content-image">
        <img src={{content.image.url}} alt="サンプル" style='border-radius:28px;' width="348" height="348" class='image'/>
        <div class='like-ikons'>
            <form method="post" class='like-form'>
            {% csrf_token %}
            {% if like %}
                <button type="submit" class='like-button' name='like'>
                    <img id="like-ikon1" src="{% static 'svg/コンポーネント 14 – 2 (1).svg' %}"/>
                </button>    
            {% else %}
                <button type="submit" class='like-button' name='like'>
                    <img id="like-ikon2" src="{% static 'svg/コンポーネント 14 – 2.svg' %}"/>
                </button>  
            {% endif %}
            </form>    
        </div>   
    </div>
    <div class="content-content">
        <div class="content-detail1">
            <div class='content-date'>{{content.date}}</div>
            <div class="content-place"><img id="image-display_origin3" src="{% static 'svg/グループ 271.svg' %}"/>{{content.place}}</div>
            <div class="content-category"><p class='content-category_doc'>{{content.category}}</p></div>
        </div>
        <div class="content-detail2">
            {{content.comment}}
        </div>
    </div>
    <div class="form-unclicked" id='form-unclicked'>
        <table class="form-unclicked_table">
            <tr>
                <td><button id='action' class='action'><img class='form-image1' id='cross' src="{% static 'svg/グループ 352.svg' %}" /></button></td>
                <td><p class='form-document' id='form-document'>コメントを入力</p></td>
            </tr>
        </table>
    </div>
    <form method="post" enctype="multipart/form-data" class="form" id='form'>
        {% csrf_token %}
        <div class="form-content">
            <div class="form-table">{{ form.thread }}</div>  
            <div class="form-button">
                <button type="submit" class="button" name='thread1'><img class='form-image' id='deleteIcon' src="{% static 'svg/パス 335.svg' %}" /></button>
            </div>
        </div>
    </form>
    <div class='thread-whole'>
        {{content.talk}}
        {% for thread in thread %}
        <div class="threadform">
            <div class='thread1-display'>
                {% if thread.threadconnection_user.icon %}
                <img class='thread1-img' src='{{ thread.threadconnection_user.icon.url }}' style='border-radius:50px;' height='30px' width='30px'/>
                {% endif %}
                <p class='thread1-doc'>{{ thread.threadconnection_user.username }}</p>
                <p class='thread1-thread'>{{thread.thread}}</p>
            </div>
            <button class='reply-trigger' id='unclicked' >
                <p id='doc' class='unclicked-doc'>返信する</p>
                <img class='form-image3' id='img' src="{% static 'svg/グループ 352.svg' %}" />
            </button>
            <form method="post" class="replyform" id='clicked'>
                <div class='replyform-content'>
                    <button class='replybutton' type="submit" name="th" value={{forloop.counter0}}><img class='form-image2' id='deleteIcon' src="{% static 'svg/パス 335.svg' %}" /></button>
                    <div class='replyform-thread'>{{form1.threadlist}}</div>
                </div>
                {% csrf_token %}
            </form>
            <div class="thread2">
                {% for threadlist in threadlist %}
                {% if threadlist.threadlistconnection_thread == thread %}
                <div class="thread2_content">
                    {% if threadlist.threadlistconnection_user.icon %}
                    <img class='thread2-img' src='{{threadlist.threadlistconnection_user.icon.url}}' style='border-radius:50px;' height='30px' width='30px'/>
                    {% endif %}
                    <div class="thread2-doc">{{threadlist.threadlistconnection_user.username}}</div>
                    <div class="thread2-thread">{{threadlist.threadlist}}</div>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock main %}
{% block script %}
    <script type="text/javascript" src="{% static 'javascript/friends_content.js' %}"></script>
</body>
{% endblock script %}
</html>

intern_project/cookapp/templates/cookapp/friends_list.html
{% extends 'cookapp/base.html' %}
{% load static %}
<!doctype html>
<html lang="ja">
    
{% block extrastyle %}

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/friends_list.css' %}" />
    <title>友達一覧</title>

{% endblock extrastyle %}

{% block header %}
    
        <div class="title-and-arrow">
            <a href="{{request.META.HTTP_REFERER}}"><img class='arrow-img' src="{% static 'svg/←(黒).svg' %}" /></a>
            <h1 class='title'>友だち</h1>
        </div>
        <div class="number-of-friends">{{number}}人</div>
    {% endblock header %}

{% block main %}


    {% if friendslist %}
        {% for f in friendslist %}
          {% if f.users == user %}     
            {% if f.current_user.icon %}
                <a href="{% url 'friends_profile' f.current_user.id %}" class="friends" style="cursor:default;color:inherit;text-decoration:none;">
                    <div class='friend'>
                        <img src="{{f.current_user.icon.url}}" alt="サンプル" style='border-radius:50px;' width="30" height="30">
                        <p>{{f.current_user.username}}</p>
                    </div>
                </a>
            {% endif %}
          {% endif %}
        {% endfor %}
    {% endif %}

{% endblock main %}

</body>

intern_project/cookapp/templates/cookapp/friends_profile.html
{% extends 'cookapp/base.html' %}
{% load static %} 
{% load widget_tweaks %} 
<!doctype html>
<html lang="ja">
  {% block extrastyle %}
  
  <link rel="stylesheet" href="../static/css/friends_profile.css">
  
  {% endblock extrastyle %}

  
{% block header %}
    {% if user.icon %}
    <div class="header-icon"><a href=""><img src="{{user.icon.url}}" alt="" ></a></div>
    {% endif %}
    <div class='user-name'>{{user.username}}</div>
{% endblock header %}

    {% block main %}
        <div class="main-container">
            <div class="random-image">
                {% if randomcontent %}
                <a class ="" href="{% url 'friends_content' randomcontent.id %}"><img src="../media/{{randomcontent.image}}" alt="サンプル" width="84px" height="84px" class=""></a>
                {% endif %}
            </div>
            <div class="images-container">
                {% if content %}
                {% for content in content %}
                <div class="images-submitted">
                    <a class ="" href="{% url 'friends_content' content.id %}"><img src="../media/{{content.image}}" alt="サンプル" width="84px" height="84px"></a>
                </div>   
                {% endfor %}
                {% endif %}
            </div>
        </div>

    {% endblock main %}
    
</body>
</html>

intern_project/cookapp/templates/cookapp/my_content_update.html
{% extends 'cookapp/base.html' %}
{% load static %}
{% load widget_tweaks %}

    {% block extrastyle %}
        <link rel="stylesheet" href="../static/css/my_content_update.css">
        <link rel="stylesheet" href="../static/css/base.css">

    {% endblock extrastyle %}

        {% block header %}

        <div class="header-container">
           <div class=""><a href="" onclick="window.history.back(); return false;"><img src="{% static 'svg/←(黒).svg' %}" alt=""></a></div>
           <div class="">編集</div>
        </div>

        {% endblock header %}

        {% block main %}

        <div class="main-container">
            <form method="POST" enctype="multipart/form-data" class='form'>
               {% csrf_token %}
                <div class="content-image" >
                   <label for="{{ form.image.id_for_label }}"><img src="{{form.image.value.url}}" id="image_preview"></label>
                   <input type="file" name="{{ form.image.html_name }}" accept="image/*" id="{{ form.image.id_for_label }}" style="display: none;">
                </div>
                <div class="public-private">{{ form.public_private }}</div>
                <div class="date fields">{{ form.date|add_class:"form-date" }}</div>
                <div class="category fields">{{ form.category|add_class:'form-width' }}</div>
                <div class="place fields">{{ form.place }}</div>
                <div class="" style="color:#757575; font-size: 12px;">例）大阪府・東京都など都道府県、または家</div>
                <div class="comment fields">{{ form.comment|add_class:'form-width' }}</div>
                <div class="update-button"><button type="submit">更新</button></div>
            </form>
        </div>
        
        {% endblock main %}
    {% block script %}
    <script src="../static/javascript/my_content_update.js"></script>
    {% endblock script %}

intern_project/cookapp/templates/cookapp/signup.html
{% load static %} 
{% load widget_tweaks %} 
<!doctype html>
<html lang="ja">
<head>
        <meta charset="utf-8" name="viewport" content="width=device-width">
        <link rel="stylesheet" href="../static/css/signup.css">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Kosugi+Maru&display=swap" rel="stylesheet">
</head>
<body>
    <header >
        <div class="header-wrapper">
            <div class="header-arrow"><a href="{% url 'top' %}"><img src="{% static 'svg/←.svg' %}" alt="" ></a></div>
            <h1 class="container">アカウントを作る</h1>
        </div>
    </header>
    <main>
        <div class="main-wrapper">
            <form method = "post" enctype = "multipart/form-data" >
                    {% csrf_token %}
                <div class="icon-form">
                    <img src="{% static 'png/ロゴ顔だけ.png' %}" alt="" id="image_preview" class="signup-image">
                    <label for="id_icon"><div class="input-icon-file"><img src="{% static 'svg/グループ 3.svg' %}" alt="" ></div></label>
                    {{form.icon|add_class:"form-hidden"}}
                </div>
                <div class="container signup-form">
                    <div class="container form-font">名前（20文字まで）<span class="required-mark">*</span></div>
                    <div class="container ">{{form.username|add_class:"form-label"}}
                        {{form.username.errors}}
                    </div>
                </div>
                <div class="container signup-form">
                    <div class="container form-font">メールアドレス<span class="required-mark">*</span></div>
                    <div class="container ">{{form.email|add_class:"form-label"}}
                    <div class="container form-error">{{form.email.errors}}</div>
                    </div>
                </div>
                <div class="container signup-form">
                    <div class="container form-font">パスワード<span class="required-mark">*</span></div>
                    <div class="container ">{{form.password1|add_class:"form-label"}}</div>
                </div>
                <div class="container signup-form">
                    <div class="container form-font">パスワード（確認）<span class="required-mark">*</span></div>
                    <div class="container ">{{form.password2|add_class:"form-label"}}
                    <div class="container form-error">{{form.password2.errors}}</div>
                    </div>
                </div>
                <div class="container"><span class="container required-mark">*必須</span></div>
                <div class="container button"><button type = "submit" >登録</button></div>  
            </form>
        </div>
    </main>
    <footer class="">
        <div class="footer-image"><img src="{% static 'png/login_signup1.png' %}" ></div>
    </footer>
<script src="{% static 'javascript/signup.js' %}"></script>
</body>
</html>